
[sider]
	debug = 0
	start.fullscreen = 1
	full-screen = 1
	width = 1920
	height = 1080
	address.ignore.settings.dat = 1
	close.on.exit = 1
	start.minimized = 1
	free.side.select = 1
	livecpk.enabled = 1
	match-stats.enabled = 1
	exe.name = "\FL_2026.exe"
	start.ini = "FL26://REAL_PES_2025"
	ini.name = "REAL_PES_2025.ini"
	match.minutes = 0



	cpk.root = ".\livecpk"
	cpk.root = ".\livecpk\root"
	cpk.root = ".\livecpk\Menu"
	cpk.root = ".\livecpk\MenuC1987"
	cpk.root = ".\livecpk\Logos_FL26"
	cpk.root = ".\livecpk\Goal Sound"
	# cpk.root = ".\livecpk\Chants"
	cpk.root = ".\livecpk\healthArrow"
	cpk.root = ".\livecpk\F4L_REALISTIC_GAMEPLAY"
	cpk.root = ".\livecpk\goalnets_25-26"
	cpk.root = ".\livecpk\Adboard"
	#cpk.root = ".\livecpk\Adboards"
	cpk.root = ".\livecpk\UIColors"
	cpk.root = ".\livecpk\Faces"
	cpk.root = ".\livecpk\EPL Font"
	cpk.root = ".\livecpk\EPL Emblem"
	cpk.root = ".\livecpk\Dirt_Clotch_Stains"
	cpk.root = ".\content\Stadium_CornerFlag"
	cpk.root = ".\livecpk\slotkits"
	cpk.root = ".\livecpk\Anthems"
	#cpk.root = ".\livecpk\World Cup 2026 Font"

	cpk.root = ".\livecpk\Add-On\Arm e Thigh"
	cpk.root = ".\livecpk\Add-On\New Model_Global"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Extra Curved Legs"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Grip Socks_Extra Long"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Grip Socks_Long"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Grip Socks_Short"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Shirt_Baggy"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Shirt_Out"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Shirt_Tucked In"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Shorts_Baggy"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Shorts_Shorter"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Sleeves_Huge Arms"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Sleeves_Longer Inner"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Sleeves_Rolled up"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Sleeves_Shorter"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Sleeves_Shorter Inner"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_Force Long"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_Force Normal"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_Force Short"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_HolesxMoiduran"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_Mid-High"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Socks_Mid-Low"
	cpk.root = ".\livecpk\Add-On\New Model_Special\Wrist Tape_Longer"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xGraduco_Special_Socks"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xMoiduran_Special Body"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xReferee"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin1\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin1\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin2\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin2\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin3\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin3\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin4\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin4\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin5\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin5\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin6\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin6\right hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin7\left hand"
	cpk.root = ".\livecpk\Add-On\New Model_Special\xTexture_Hand Tape\skin7\right hand"
	cpk.root = ".\livecpk\kitserver special character fonts"
	cpk.root = ".\livecpk\RefColor"
	cpk.root = ".\livecpk\boot-AddOn"
	cpk.root = ".\livecpk\boot-root"
	cpk.root = ".\livecpk\Slotkits_V2"
	cpk.root = ".\livecpk\Next Gen Graphics"
	cpk.root = ".\livecpk\Mini Faces"
	cpk.root = ".\livecpk\Sub Bibs"
	cpk.root = ".\livecpk\Stadium Announcer"
	cpk.root = ".\livecpk\NoBallX"
	cpk.root = ".\livecpk\NT Flags_Badges\AFC"
	cpk.root = ".\livecpk\NT Flags_Badges\CAF"
	cpk.root = ".\livecpk\NT Flags_Badges\CONCACAF"
	cpk.root = ".\livecpk\NT Flags_Badges\Confederations"
	cpk.root = ".\livecpk\NT Flags_Badges\CONMEBOL"
	cpk.root = ".\livecpk\NT Flags_Badges\OFC"
	cpk.root = ".\livecpk\NT Flags_Badges\UEFA"
	cpk.root = ".\livecpk\scan_textures_enhanced"
	cpk.root = ".\livecpk\SoundtrackServer"
	cpk.root = ".\livecpk\IntroServer"



	lua.enabled = 1
	luajit.ext.enabled = 1
	lua.module = "lib\CommonLib.lua"
	lua.module = "lib\nesalib.lua"
	lua.module = "Al-Manager.lua"
	lua.module = "common\stadiums.lua"
	#lua.module = "common\scoreboards.lua"
	lua.module = "ScoreboardServer.lua"
	;lua.module = "scoreboard-hexx.lua"
	lua.module = "CustomExhibitionMatch.lua"
	lua.module = "common\cinematics.lua"
	lua.module = "common\cinematicsB.lua"
	lua.module = "common\referee.lua"
	#lua.module = "common\audio.lua"
	lua.module = "common\kits.lua"
	#lua.module = "SleeveBadge-ArmbandServer.lua"
	lua.module = "common\SleeveBadge.lua"
	#lua.module = "common\Fans-Server.lua"
	lua.module = "FansServer.lua"
	#lua.module = "common\omb.lua"
	lua.module = "env.lua"
	lua.module = "camera.lua"
	lua.module = "matchset.lua"
	lua.module = "nets.lua"
	lua.module = "movieintro.lua"
	lua.module = "MenuServer.lua"
	lua.module = "BallServer.lua"
	lua.module = "goalnets\goalnets_25-26.lua"
	lua.module = "Chants-Server.lua"
	lua.module = "GoalSongServer.lua"
	lua.module = "Entrance_fix.lua"
	lua.module = "Entrance.lua"
	lua.module = "tournament_anth_tunnel.lua"
	lua.module = "tunnel.lua"
	lua.module = "UIColors.lua"
	lua.module = "trophy.lua"
	lua.module = "netblock.lua"
	lua.module = "DynamicWideCam.lua"
	lua.module = "FanViewCam.lua"
	lua.module = "BroadCastCam.lua"
	lua.module = "CommonCam.lua"
	lua.module = "PenaltyCam.lua"
	lua.module = "ReplayCam.lua"
	lua.module = "StadiumCam.lua"
	lua.module = "VerticalCam.lua"
	lua.module = "WeatherConditions.lua"
	lua.module = "TurfLoader.lua"
	lua.module = "Shape-turf-loader.lua"
	lua.module = "SubBoard.lua"
	#lua.module = "StadiumServer.lua"
	lua.module = "tracer.lua"
	lua.module = "Stadium_Banner.lua"
	lua.module = "Stadium_Board.lua"
	lua.module = "Stadium_CornerFlag.lua"
	lua.module = "Stadium_Tunnel.lua"
	lua.module = "common\POTM_Server.lua"
	lua.module = "core_noscript.lua"
	lua.module = "legend_balance.lua"
	lua.module = "cpu_realism.lua"
	lua.module = "ml_bal_noscript.lua"
	lua.module = "noscript.lua"
	lua.module = "injury_mod.lua"
	#lua.module = "aspectratio.lua"
	lua.module = "RefKitServer.lua"
	lua.module = "kserv.lua"
	lua.module = "BudgetSetter.lua"
	lua.module = "BallBoysServer.lua"
	lua.module = "BibServer.lua"
	lua.module = "randomWhistle_gpt.lua"
	lua.module = "GameplayLoader.lua"
	lua.module = "SoundServer.lua"
	lua.module = "SoundtrackServer.lua"
	lua.module = "kitglobal.lua"
	lua.module = "IntroServer.lua"

	overlay.enabled = 1
	overlay.on-from-start = 0
	overlay.location = "bottom"
	overlay.font-size = -1
	overlay.font = "Arial"
	overlay.vkey.toggle = 0x20
	overlay.vkey.next-module = 0x31
	overlay.vkey.prev-module = 0xc0
	overlay.background-color = "202020c0"
	overlay.text-color = "bbbbbbc0"
	overlay.image-alpha-max = 0.8
	overlay.toggle.sound = "click.wav"
	overlay.toggle.sound-volume = 0.5
	vkey.reload-1 = 0x10
	vkey.reload-2 = 0x52
